/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Dashboard colors (first page)
        'on-tertiary-container': '#696379',
        error: '#ba1a1a',
        'on-primary-container': '#357063',
        'on-surface-variant': '#404946',
        'tertiary-fixed': '#e7def8',
        'surface-tint': '#2d685c',
        background: '#fbfaf8',
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        primary: '#2d685c',
        'on-secondary-fixed': '#2b160a',
        outline: '#707976',
        'primary-container': '#b4f1e1',
        'surface-container': '#edeeef',
        'primary-fixed': '#b2efdf',
        'secondary-fixed': '#ffdbca',
        'inverse-on-surface': '#f0f1f2',
        'surface-dim': '#d9dadb',
        'on-secondary-container': '#795a4a',
        'inverse-primary': '#96d2c3',
        secondary: '#765848',
        'secondary-fixed-dim': '#e6beab',
        'surface-container-low': '#f3f4f5',
        'secondary-container': '#fdd4c0',
        'on-secondary-fixed-variant': '#5c4132',
        surface: '#fbfaf8',
        tertiary: '#615b71',
        'surface-variant': '#e1e3e4',
        'outline-variant': '#bfc9c5',
        'on-primary-fixed': '#00201a',
        'inverse-surface': '#2e3132',
        'surface-container-high': '#e7e8e9',
        'on-secondary': '#ffffff',
        'surface-bright': '#fbfaf8',
        'tertiary-fixed-dim': '#cbc3dc',
        'on-surface': '#191c1d',
        'primary-fixed-dim': '#96d2c3',
        'surface-container-highest': '#e1e3e4',
        'on-tertiary-fixed': '#1d192b',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#494458',
        'on-primary': '#ffffff',
        'on-primary-fixed-variant': '#0e5044',
        'tertiary-container': '#eae1fb',
        'on-error-container': '#93000a',
        'on-background': '#191c1d',
        'on-tertiary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
        sketchy: '255px 15px 225px 15px/15px 225px 15px 255px',
      },
      spacing: {
        'element-gap': '16px',
        'container-padding': '32px',
        'base-unit': '8px',
        'section-gap': '64px',
        gutter: '24px',
      },
      fontFamily: {
        'headline-md': ['Quicksand', 'sans-serif'],
        'body-md': ['Nunito Sans', 'sans-serif'],
        'headline-lg-mobile': ['Quicksand', 'sans-serif'],
        'label-caps': ['Quicksand', 'sans-serif'],
        'body-lg': ['Nunito Sans', 'sans-serif'],
        'headline-xl': ['Quicksand', 'sans-serif'],
        'headline-lg': ['Quicksand', 'sans-serif'],
        'handwritten': ['Kalam', 'cursive'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
      backgroundImage: {
        'ruled-paper': 'linear-gradient(#96d2c3 1px, transparent 1px)',
        'margin-line': 'linear-gradient(90deg, transparent 40px, #ffdad6 40px, #ffdad6 42px, transparent 42px)',
      },
      boxShadow: {
        'cloud': '0px 10px 30px rgba(0,0,0,0.04)',
        'card': '2px 4px 12px rgba(0,0,0,0.05)',
        'sketchy': '3px 4px 0px rgba(0,0,0,0.1)',
      },
    },
  },
  plugins: [],
}